[default]
mongo_uri = "mongodb://localhost:27017/blog"
title = "Meu blog"
extensions = [
    "blog.database:configure",
    "blog.commands:configure",
    "flask_bootstrap:Bootstrap",
    "blog.views:configure",
    "blog.plugins:configure",
]
